#!/usr/bin/env python
import sys
import matrix
import fas

if len(sys.argv) > 1:
  f = io.open(sys.argv[1])
else:
  f = sys.stdin

mx = matrix.parse(f)

order = fas.optimise(mx)

print "Score: %f" % fas.score(mx, order)
print "Lower bound on best score: %f" % fas.lower_bound(mx)
print "Optimal ordering: %s" % ' '.join([str(i) for i in order])
